### ISSUE TITLE
Getting below error while installing CS on Linux and Windows hosts

### ISSUE THREAD

**Issue by zurrehma** [CrowdStrike/ansible_collection_falcon#100]
`
TASK [crowdstrike.falcon.falcon_installation : CrowdStrike Falcon | Authenticate to CrowdStrike API] *******************************************************************************************************
fatal: [104.43.209.70]: FAILED! => {"changed": false, "connection": "close", "content": "", "content_length": "0", "date": "Sun, 02 Jan 2022 22:56:42 GMT", "elapsed": 0, "location": "https://api.us-2.crowdstrike.com/oauth2/token", "msg": "Status code was 308 and not [201]: HTTP Error 308: Permanent Redirect", "redirected": false, "status": 308, "strict_transport_security": "max-age=31536000; includeSubDomains", "url": "https://api.crowdstrike.com/oauth2/token", "x_cs_region": "us-2", "x_cs_traceid": "b4562a45-4f1c-41a1-801e-14195134444a", "x_ratelimit_limit": "300", "x_ratelimit_remaining": "299"}

TASK [crowdstrike.falcon.falcon_installation : include_tasks] **********************************************************************************************************************************************
included: /home/azureuser/.ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_installation/tasks/win_api.yml for 40.83.56.243

TASK [crowdstrike.falcon.falcon_installation : CrowdStrike Falcon | Authenticate to CrowdStrike API] *******************************************************************************************************
fatal: [40.83.56.243]: FAILED! => {"changed": false, "character_set": null, "content": "", "content_encoding": "", "content_length": "0", "content_type": "", "cookies": [], "date": "Sun, 02 Jan 2022 22:56:45 GMT", "elapsed": 0, "headers": ["Strict-Transport-Security", "X-Cs-Region", "X-Cs-Traceid", "X-Ratelimit-Limit", "X-Ratelimit-Remaining", "Content-Length", "Date", "Location"], "is_from_cache": false, "is_mutually_authenticated": false, "last_modified": "2022-01-02T22:56:45.7712702+00:00", "location": "https://api.us-2.crowdstrike.com/oauth2/token", "method": "POST", "msg": "Status code of request '308' is not in list of valid status codes 201 : 308'.", "protocol_version": {"Build": -1, "Major": 1, "MajorRevision": -1, "Minor": 1, "MinorRevision": -1, "Revision": -1}, "response_uri": "https://api.crowdstrike.com/oauth2/token", "server": "", "status_code": 308, "status_description": "Permanent Redirect", "strict_transport_security": "max-age=31536000; includeSubDomains", "supports_headers": true, "url": "https://api.crowdstrike.com/oauth2/token", "x_cs_region": "us-2", "x_cs_traceid": "790838bc-720b-43a2-a0ae-996d11e6729a", "x_ratelimit_limit": "300", "x_ratelimit_remaining": "299"}
`

**Comment by redhatrises** [comment]
Hello,

Looks like you are trying to connect to api.us-2.crowdstrike.com. The default setting that is used is api.crowdstrike.com. Pointing to the correct Falcon Cloud should solve your issue. This should be fixed in the next release.

**Comment by shawnharvick** [comment]
I am also running into this issue.  I am not specifically trying to connect to api.us-2.crowdstrike.com, just using the default, but still getting the error.  

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Authenticate to CrowdStrike API] ****************************************************************************************************************
fatal: [host.local]: FAILED! => {"changed": false, "connection": "close", "content": "", "content_length": "0", "date": "Thu, 13 Jan 2022 16:34:28 GMT", "elapsed": 0, "location": "https://api.us-2.crowdstrike.com/oauth2/token", "msg": "Status code was 308 and not [201]: HTTP Error 308: Permanent Redirect", "redirected": false, "status": 308, "strict_transport_security": "max-age=31536000; includeSubDomains", "url": "https://api.crowdstrike.com/oauth2/token", "x_cs_region": "us-2", "x_cs_traceid": "473103e1-44db-4546-b613-5dbd3065b21b", "x_ratelimit_limit": "300", "x_ratelimit_remaining": "299"}

**Comment by redhatrises** [comment]
Hello,

Looks like your CS region that you are assigned is `us-2`. Please make sure to create your API client id and client secret with the appropriate permissions are created in `us-2`.

**Comment by shawnharvick** [comment]
Hello I can confirm that I created the client id and secret in us-2

**Comment by redhatrises** [comment]
Can you provide a sanitized version of the playbook that you are running?

**Comment by shawnharvick** [comment]
Here you go, thanks

[cs-install-san.yml.txt](https://github.com/CrowdStrike/ansible_collection_falcon/files/7871556/cs-install-san.yml.txt)

**Comment by redhatrises** [comment]
@shawnharvick can you try the changes in #137 ?

**Comment by carlosmmatos** [comment]
@shawnharvick @zurrehma this should be fixed in #137 as @redhatrises pointed out to. But to give further context, this was an issue with the win_uri Ansible module not being able to follow a redirect appropriately. The new fix takes this into account, however we should also mention that you could also provide the right URL to use for authenticating to CS. 

For example, since the credentials being used here were for us-2, then you could set the following vars:
```yaml
falcon_cloud: "api.us-2.crowdstrike.com"
falcon_cloud_autodiscover: no
```
With the above set, then there wouldn't be a need for a redirect to occur when authenticating with the API.

Please let us know if you are still having this issue.

**Comment by Antse** [comment]
@carlosmmatos , do you know when this will be released ?

**Comment by carlosmmatos** [comment]
@Antse We are finalizing a few things, but expect it soon.

**Comment by carlosmmatos** [comment]
@Antse A new release was published about 16 hours ago and is available both here and on Ansible Galaxy. For anyone that uses Automation Hub, we will be uploading the new release soon as well.

Going to close this issue as the fixes identified should resolve this issue. Feel free to reopen or open a new issue if this is not the case.

**Comment by Antse** [comment]
> @Antse A new release was published about 16 hours ago and is available both here and on Ansible Galaxy. For anyone that uses Automation Hub, we will be uploading the new release soon as well.
> 
> Going to close this issue as the fixes identified should resolve this issue. Feel free to reopen or open a new issue if this is not the case.

Confirmed it’s fixed
