### ISSUE TITLE
Ubuntu 20.04 - RHEL 9 - issue with 3.2.18 and 6.41.13804

### ISSUE THREAD

**Issue by TyraelTLK** [CrowdStrike/ansible_collection_falcon#226]
I'm trying to running the collection with:
falcon_sensor_version_decrement: 0

and it doesn't work on Ubuntu 20.04.
I'll end up with only the package crowdstrike-cs-falconhoseclient 2.11.0 installed
If I don't set falcon_sensor_version_decrement: 0 falcon-sensor 6.38.0-13501 is correctly installed

**Comment by TyraelTLK** [comment]
Specifying -e 'falcon_sensor_version="6.38.13501"' works.
Specifying -e 'falcon_sensor_version="6.40.13707"' works.
Specifying -e 'falcon_sensor_version="6.41.13804"' **does NOT** work.

**Comment by carlosmmatos** [comment]
Looks like there is an issue with the API for getting the installers.. For some odd reason it's trying to pull in the Falcon SIEM controller (WHICH IS MOST DEFINITELY SHOULD NOT).. I will be asking the API owners to look into this.

As for your second question - when you specify `falcon_sensor_version="6.41.13804"` - what is the error you are getting?

**Comment by carlosmmatos** [comment]
@TyraelTLK The API issue has been resolved. If you have issues with installing the latest sensor version, my guess is that it's related to the kernel version.

**Comment by TyraelTLK** [comment]
Hi @carlosmmatos, I still have the issue:

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Install Falcon Sensor Package (Linux)] ********************************************************
changed: [] => {"changed": true, "stderr": "", "stderr_lines": [], "stdout": "Selecting previously unselected package crowdstrike-cs-falconhoseclient.\n(Reading database ... 169355 files and directories currently installed.)\nPreparing to unpack .../crowdstrike-cs-falconhoseclient_2.11.0_amd64.deb ...\nUnpacking crowdstrike-cs-falconhoseclient (2.11.0) ...\nSetting up crowdstrike-cs-falconhoseclient (2.11.0) ...\n", "stdout_lines": ["Selecting previously unselected package crowdstrike-cs-falconhoseclient.", "(Reading database ... 169355 files and directories currently installed.)", "Preparing to unpack .../crowdstrike-cs-falconhoseclient_2.11.0_amd64.deb ...", "Unpacking crowdstrike-cs-falconhoseclient (2.11.0) ...", "Setting up crowdstrike-cs-falconhoseclient (2.11.0) ..."]}

We are on US-2.

**Comment by TyraelTLK** [comment]
Specifying `falcon_sensor_version="6.41.13804"` works on Ubuntu 20.04 but does not work on RHEL 9:

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Validate Sensor request] ***
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No Falcon Sensor was found! If passing in falcon_sensor_version, ensure it is correct!"}

**Comment by TyraelTLK** [comment]
RHEL 9 with `falcon_sensor_version_decrement="0" falcon_api_enable_no_log=false`
```
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Build API Sensor Query] *************************
ok: [localhost] => {"ansible_facts": {"falcon_os_query": "os:\"RHEL/CentOS/Oracle\"+os_version:\"9\""}, "changed": false}
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Get list of filtered Falcon sensors] ************
ok: [localhost] => {"changed": false, "connection": "close", "content": "{\n \"meta\": {\n  \"query_time\": 0.09740231,\n  \"powered_by\": \"binserv\",\n  \"trace_id\": \"\"\n },\n \"errors\": [],\n \"resources\": []\n}\n", "content_length": "159", "content_type": "application/json", "cookies": {}, "cookies_string": "", "date": "Fri, 05 Aug 2022 07:56:34 GMT", "elapsed": 0, "json": {"errors": [], "meta": {"powered_by": "binserv", "query_time": 0.09740231, "trace_id": ""}, "resources": []}, "msg": "OK (159 bytes)", "redirected": false, "server": "nginx", "status": 200, "strict_transport_security": "max-age=15724800; includeSubDomains, max-age=31536000; includeSubDomains", "url": "https://api.us-2.crowdstrike.com/sensors/combined/installers/v1?filter=os%3A%22RHEL/CentOS/Oracle%22%2Bos_version%3A%229%22", "x_cs_region": "us-2", "x_cs_traceid": "", "x_ratelimit_limit": "6000", "x_ratelimit_remaining": "5987"}
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Validate Sensor request] ************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No Falcon Sensor was found! If passing in falcon_sensor_version, ensure it is correct!"}
```

**Comment by carlosmmatos** [comment]
@TyraelTLK I can confirm RHEL 9 is an issue. Again, seems to be related to our API's. It looks like they changed the os query to `RHEL` instead of `RHEL/CentOS/Oracle`. We will create a fix for this soon. 

In the meantime, you can work-around this issue by passing in an extra var to override the `os:` portion of the `falcon_os_query` command by setting the following:

```yaml
falcon_target_os: 'RHEL'
```

This should override the role/task variable.

**Comment by TyraelTLK** [comment]
@carlosmmatos
Now Ubuntu 20.04 works fine.
`falcon_target_os: 'RHEL'` works as a work-around for RHEL9. Thanks.

**Comment by carlosmmatos** [comment]
@TyraelTLK Glad to know it's working. I will be submitting a PR to fix the RHEL issue today.
